### ISSUE TITLE
Error in the code

### ISSUE THREAD

**Issue by SudheerReddyBandi** [I-Hope-Peace/KPCAMNet#2]
Traceback (most recent call last):
  File "train_KPCAMNet.py", line 9, in <module>
    from Methodology.Deep.KPCAMNet.KPCANet import KernelPCANet
ModuleNotFoundError: No module named 'Methodology'

**Comment by flying318** [comment]
It's an error caused by path. You should modify the path according to your file. An example follows:
if your current work path is '**_../KPCAMNet_**', you can write it as '**_from KPCANet import KernelPCANet_**' directly. 
Good luck.

**Comment by ChenHongruixuan** [comment]
Thank you for helping answer the question!
